import {
  ALL_COUNTRIES,
  CommunicationStyle,
  ConflictResolutionStyle,
  CoreValue,
  DrinkingHabit,
  EmotionalReadiness,
  ExerciseFrequency,
  ISLAM_SECTS,
  MarriageTimeline,
  OCCUPATIONS,
  PersonalityTrait,
  PolygamyStance,
  RELIGIONS,
  RelationshipType,
  RelocationWillingness,
  SmokingHabit,
  SubscriptionTier,
  TIER_CONFIG,
  WantsChildren,
  ChildrenStatus,
  DietType,
} from '@kujuana/shared';

export const options = {
  tiers: [SubscriptionTier.Standard, SubscriptionTier.Priority, SubscriptionTier.VIP],
  countries: ALL_COUNTRIES,
  religions: RELIGIONS,
  islamSects: ISLAM_SECTS,
  occupations: OCCUPATIONS,
  educationLevels: [
    'Secondary School',
    'Diploma',
    'Bachelor Degree',
    'Masters Degree',
    'Doctorate',
    'Other',
  ],
  maritalStatuses: ['single', 'divorced', 'widowed'] as const,
  genders: ['male', 'female'] as const,
  smokingHabits: Object.values(SmokingHabit),
  drinkingHabits: Object.values(DrinkingHabit),
  diets: Object.values(DietType),
  exerciseFrequencies: Object.values(ExerciseFrequency),
  childrenStatuses: Object.values(ChildrenStatus),
  wantsChildren: Object.values(WantsChildren),
  relocation: Object.values(RelocationWillingness),
  personalityTraits: Object.values(PersonalityTrait),
  relationshipTypes: Object.values(RelationshipType),
  marriageTimelines: Object.values(MarriageTimeline),
  polygamyStances: Object.values(PolygamyStance),
  coreValues: Object.values(CoreValue),
  emotionalReadiness: Object.values(EmotionalReadiness),
  communicationStyles: Object.values(CommunicationStyle),
  conflictStyles: Object.values(ConflictResolutionStyle),
};

export const tierLabels = Object.fromEntries(
  Object.entries(TIER_CONFIG).map(([key, value]) => [key, value.label]),
);
